-- Polaris MVP reference schema for SQLite 3.
-- IDs are UUID strings generated by the application.
-- JSON columns are stored as TEXT and validated at the application boundary.

PRAGMA foreign_keys = ON;

CREATE TABLE analysis_sessions (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('ACTIVE', 'READY_TO_FINALIZE', 'COMPLETED')),
  focus_areas_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  completed_at TEXT
);

CREATE TABLE messages (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES analysis_sessions(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('USER', 'ASSISTANT')),
  content TEXT NOT NULL,
  question_target TEXT CHECK (question_target IN (
    'CAN', 'WANT', 'ENERGY', 'CONTEXT', 'EXPERIENCE_DETAIL',
    'CONTRADICTION', 'CONFIRMATION'
  )),
  client_message_id TEXT UNIQUE,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_messages_session_created
  ON messages(session_id, created_at);

CREATE TABLE experiences (
  id TEXT PRIMARY KEY,
  source_session_id TEXT REFERENCES analysis_sessions(id) ON DELETE SET NULL,
  type TEXT NOT NULL CHECK (type IN (
    'ENGAGED', 'ACHIEVEMENT', 'CHALLENGE', 'DRAINING_SUCCESS',
    'TEAM_CONFLICT', 'OTHER'
  )),
  title TEXT NOT NULL,
  situation TEXT NOT NULL,
  goal TEXT,
  role TEXT NOT NULL,
  options_json TEXT NOT NULL DEFAULT '[]',
  decision TEXT,
  decision_reason TEXT,
  actions_json TEXT NOT NULL,
  result TEXT,
  positive_emotion TEXT,
  negative_emotion TEXT,
  energy_change INTEGER NOT NULL CHECK (energy_change BETWEEN -2 AND 2),
  environment_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL CHECK (status IN ('DRAFT', 'CONFIRMED')),
  confirmed_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_experiences_status ON experiences(status);

CREATE TABLE experience_quotes (
  id TEXT PRIMARY KEY,
  experience_id TEXT NOT NULL REFERENCES experiences(id) ON DELETE CASCADE,
  message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE RESTRICT,
  quote TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (experience_id, message_id, quote)
);

CREATE TABLE evidence_items (
  id TEXT PRIMARY KEY,
  experience_id TEXT NOT NULL REFERENCES experiences(id) ON DELETE CASCADE,
  message_id TEXT REFERENCES messages(id) ON DELETE SET NULL,
  category TEXT NOT NULL CHECK (category IN ('CAN', 'WANT', 'ENERGY', 'CONTEXT')),
  statement TEXT NOT NULL,
  support_type TEXT NOT NULL CHECK (support_type IN ('SUPPORT', 'COUNTER', 'UNKNOWN')),
  quote TEXT NOT NULL,
  interpretation TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_evidence_experience ON evidence_items(experience_id);
CREATE INDEX idx_evidence_category ON evidence_items(category);

CREATE TABLE career_hypotheses (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('CAN', 'WANT', 'ENERGY', 'CONTEXT')),
  ai_statement TEXT NOT NULL,
  display_statement TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN (
    'CONFIRMED_PATTERN', 'CURRENT_HYPOTHESIS', 'INSUFFICIENT_EVIDENCE'
  )),
  enabling_conditions_json TEXT NOT NULL DEFAULT '[]',
  risk_conditions_json TEXT NOT NULL DEFAULT '[]',
  user_assessment TEXT NOT NULL CHECK (user_assessment IN (
    'UNREVIEWED', 'MATCHES', 'PARTIALLY_MATCHES',
    'DOES_NOT_MATCH', 'NEEDS_EXPLORATION'
  )),
  user_note TEXT,
  internal_confidence REAL CHECK (
    internal_confidence IS NULL OR internal_confidence BETWEEN 0 AND 1
  ),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_hypotheses_category_status
  ON career_hypotheses(category, status);

CREATE TABLE hypothesis_evidence (
  hypothesis_id TEXT NOT NULL REFERENCES career_hypotheses(id) ON DELETE CASCADE,
  evidence_id TEXT NOT NULL REFERENCES evidence_items(id) ON DELETE RESTRICT,
  PRIMARY KEY (hypothesis_id, evidence_id)
);

CREATE TABLE career_reports (
  id TEXT PRIMARY KEY,
  source_session_id TEXT NOT NULL REFERENCES analysis_sessions(id) ON DELETE RESTRICT,
  summary TEXT NOT NULL,
  confirmed_can_json TEXT NOT NULL DEFAULT '[]',
  current_hypotheses_json TEXT NOT NULL DEFAULT '[]',
  wants_json TEXT NOT NULL DEFAULT '[]',
  energizing_activities_json TEXT NOT NULL DEFAULT '[]',
  draining_activities_json TEXT NOT NULL DEFAULT '[]',
  enabling_contexts_json TEXT NOT NULL DEFAULT '[]',
  risk_contexts_json TEXT NOT NULL DEFAULT '[]',
  must_conditions_json TEXT NOT NULL DEFAULT '[]',
  prefer_conditions_json TEXT NOT NULL DEFAULT '[]',
  avoid_conditions_json TEXT NOT NULL DEFAULT '[]',
  verify_conditions_json TEXT NOT NULL DEFAULT '[]',
  next_experiments_json TEXT NOT NULL DEFAULT '[]',
  is_stale INTEGER NOT NULL DEFAULT 0 CHECK (is_stale IN (0, 1)),
  generated_at TEXT NOT NULL
);

CREATE INDEX idx_career_reports_generated ON career_reports(generated_at DESC);

CREATE TABLE companies (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  target_role TEXT,
  origin TEXT NOT NULL CHECK (origin IN ('USER_REGISTERED', 'CURATED')),
  official_url TEXT,
  career_url TEXT,
  recommendation_eligible INTEGER NOT NULL DEFAULT 0 CHECK (recommendation_eligible IN (0, 1)),
  note TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_companies_recommendation_eligible
  ON companies(recommendation_eligible);

CREATE TABLE company_sources (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('URL', 'TEXT', 'PDF', 'DOCX', 'TXT')),
  trust_level TEXT NOT NULL CHECK (trust_level IN (
    'OFFICIAL', 'USER_PROVIDED_UNVERIFIED'
  )),
  title TEXT NOT NULL,
  source_url TEXT,
  raw_text TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  retrieved_at TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_company_sources_company ON company_sources(company_id);

CREATE TABLE company_facts (
  id TEXT PRIMARY KEY,
  company_source_id TEXT NOT NULL REFERENCES company_sources(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN (
    'MISSION', 'BUSINESS', 'PRODUCT_OR_SERVICE', 'DESIRED_CANDIDATE',
    'REQUIRED_SKILL', 'WORK_ENVIRONMENT', 'INTERNSHIP_DETAIL',
    'ELIGIBILITY', 'DEADLINE', 'LOCATION', 'WORK_STYLE', 'OTHER'
  )),
  fact TEXT NOT NULL,
  evidence_quote TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_company_facts_source ON company_facts(company_source_id);
CREATE INDEX idx_company_facts_category ON company_facts(category);

CREATE TABLE es_documents (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  target_role TEXT,
  question TEXT NOT NULL,
  character_limit INTEGER NOT NULL CHECK (character_limit BETWEEN 1 AND 10000),
  original_text TEXT NOT NULL,
  selected_experience_ids_json TEXT NOT NULL DEFAULT '[]',
  emphasis_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL CHECK (status IN ('DRAFT', 'ANALYZED', 'REVISED', 'VERIFIED')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_es_documents_company ON es_documents(company_id);

CREATE TABLE es_analyses (
  id TEXT PRIMARY KEY,
  es_document_id TEXT NOT NULL REFERENCES es_documents(id) ON DELETE CASCADE,
  revision_id TEXT,
  source_kind TEXT NOT NULL CHECK (source_kind IN ('ORIGINAL', 'REVISION')),
  freshness TEXT NOT NULL CHECK (freshness IN ('CURRENT', 'STALE')),
  character_count INTEGER NOT NULL CHECK (character_count >= 0),
  within_character_limit INTEGER NOT NULL CHECK (within_character_limit IN (0, 1)),
  question_coverage TEXT NOT NULL CHECK (question_coverage IN (
    'ANSWERED', 'PARTIALLY_ANSWERED', 'NOT_ANSWERED'
  )),
  issues_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL
);

CREATE INDEX idx_es_analyses_document_created
  ON es_analyses(es_document_id, created_at DESC);

CREATE TABLE es_claims (
  id TEXT PRIMARY KEY,
  es_analysis_id TEXT NOT NULL REFERENCES es_analyses(id) ON DELETE CASCADE,
  sentence TEXT NOT NULL,
  claim_text TEXT NOT NULL,
  claim_type TEXT NOT NULL CHECK (claim_type IN (
    'PERSONAL_FACT', 'NUMBER', 'PERIOD', 'ROLE', 'RESULT', 'CAPABILITY',
    'COMPANY_FACT', 'MOTIVATION', 'FUTURE_GOAL'
  )),
  status TEXT NOT NULL CHECK (status IN (
    'VERIFIED', 'PARTIALLY_VERIFIED', 'NEEDS_CONFIRMATION', 'CONTRADICTED'
  )),
  explanation TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_es_claims_analysis ON es_claims(es_analysis_id);

CREATE TABLE es_claim_evidence (
  id TEXT PRIMARY KEY,
  es_claim_id TEXT NOT NULL REFERENCES es_claims(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL CHECK (source_type IN ('EXPERIENCE', 'COMPANY_FACT')),
  source_id TEXT NOT NULL,
  quote TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (es_claim_id, source_type, source_id, quote)
);

CREATE TABLE es_revisions (
  id TEXT PRIMARY KEY,
  es_document_id TEXT NOT NULL REFERENCES es_documents(id) ON DELETE CASCADE,
  based_on_analysis_id TEXT NOT NULL REFERENCES es_analyses(id) ON DELETE RESTRICT,
  freshness TEXT NOT NULL CHECK (freshness IN ('CURRENT', 'STALE')),
  revised_text TEXT NOT NULL,
  character_count INTEGER NOT NULL CHECK (character_count >= 0),
  verification_analysis_id TEXT REFERENCES es_analyses(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_es_revisions_document_created
  ON es_revisions(es_document_id, created_at DESC);

CREATE TABLE revision_changes (
  id TEXT PRIMARY KEY,
  es_revision_id TEXT NOT NULL REFERENCES es_revisions(id) ON DELETE CASCADE,
  before_text TEXT NOT NULL,
  after_text TEXT NOT NULL,
  reason TEXT NOT NULL,
  evidence_json TEXT NOT NULL DEFAULT '[]',
  decision TEXT NOT NULL CHECK (decision IN ('PENDING', 'ACCEPTED', 'REJECTED')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_revision_changes_revision ON revision_changes(es_revision_id);

CREATE TABLE recommendation_runs (
  id TEXT PRIMARY KEY,
  career_report_id TEXT NOT NULL REFERENCES career_reports(id) ON DELETE RESTRICT,
  status TEXT NOT NULL CHECK (status IN (
    'QUEUED', 'FETCHING_SOURCES', 'ANALYZING', 'COMPLETED',
    'PARTIALLY_COMPLETED', 'FAILED'
  )),
  candidate_company_ids_json TEXT NOT NULL,
  target_roles_json TEXT NOT NULL DEFAULT '[]',
  preferred_locations_json TEXT NOT NULL DEFAULT '[]',
  refresh_official_sources INTEGER NOT NULL DEFAULT 1 CHECK (refresh_official_sources IN (0, 1)),
  progress_total INTEGER NOT NULL DEFAULT 0 CHECK (progress_total >= 0),
  progress_fetched INTEGER NOT NULL DEFAULT 0 CHECK (progress_fetched >= 0),
  progress_analyzed INTEGER NOT NULL DEFAULT 0 CHECK (progress_analyzed >= 0),
  progress_failed INTEGER NOT NULL DEFAULT 0 CHECK (progress_failed >= 0),
  warnings_json TEXT NOT NULL DEFAULT '[]',
  started_at TEXT,
  completed_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_recommendation_runs_created
  ON recommendation_runs(created_at DESC);

CREATE TABLE company_recommendations (
  id TEXT PRIMARY KEY,
  recommendation_run_id TEXT NOT NULL REFERENCES recommendation_runs(id) ON DELETE CASCADE,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  slot TEXT NOT NULL CHECK (slot IN ('PRIMARY', 'CHALLENGE', 'UNEXPECTED')),
  rank INTEGER NOT NULL CHECK (rank >= 1),
  recommended_role TEXT,
  rationale TEXT NOT NULL,
  connected_experience_ids_json TEXT NOT NULL DEFAULT '[]',
  matching_conditions_json TEXT NOT NULL DEFAULT '[]',
  concerns_json TEXT NOT NULL DEFAULT '[]',
  unknowns_json TEXT NOT NULL DEFAULT '[]',
  verification_questions_json TEXT NOT NULL DEFAULT '[]',
  company_source_ids_json TEXT NOT NULL DEFAULT '[]',
  generated_at TEXT NOT NULL,
  UNIQUE (recommendation_run_id, company_id)
);

CREATE INDEX idx_company_recommendations_run_rank
  ON company_recommendations(recommendation_run_id, rank);
